# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: List files for debugging
        run: ls -l

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: role-name
          source-account-id: arn:aws:iam::281000867495:user/deploy
          role-session-name: deploy
          aws-region: us-east-1

      
      # Descargar la plantilla de CloudFormation
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
          --template-file infra-frontend.yml \
          --stack-name sp-fr-frontend-stack \
          --capabilities CAPABILITY_NAMED_IAM \
          --region us-east-1 \
          --parameter-overrides Environment=develop


      # Mostrar las URLs de salida
      - name: Get CloudFormation Outputs
        run: |
          aws cloudformation describe-stacks \
          --stack-name sp-fr-frontend-stack \
          --query "Stacks[0].Outputs" \
          --output table
