name: deploy

on:
  push:
    branches: 
      - 'develop'

jobs:
  setup-stage:
    outputs:
      env-name: ${{ steps.env-name.outputs.env }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment Name
        id: env-name
        run: echo "::set-output name=env::${{ github.ref_name }}"

  buildDev:
    needs: [setup-stage]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    environment:
      name: ${{ needs.setup-stage.outputs.env-name }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: List files for debugging
        run: ls -l

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: AKIAUC3HU62T5BIFJPBD
          role-session-name: sp-fr-front-deploy-dev
          aws-region: us-east-1
      
      # Descargar la plantilla de CloudFormation
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
          --template-file infra-frontend.yml \
          --stack-name sp-fr-frontend-stack \
          --capabilities CAPABILITY_NAMED_IAM \
          --region us-east-1 \
          --parameter-overrides Environment=develop


      # Mostrar las URLs de salida
      - name: Get CloudFormation Outputs
        run: |
          aws cloudformation describe-stacks \
          --stack-name sp-fr-frontend-stack \
          --query "Stacks[0].Outputs" \
          --output table
